//
// Created by David Paquette on 12/1/15.
//

#ifndef RTOSOBJECTORIENTEDARDUINO_SEMAPHORE_H
#define RTOSOBJECTORIENTEDARDUINO_SEMAPHORE_H


class Semaphore {

};


#endif //RTOSOBJECTORIENTEDARDUINO_SEMAPHORE_H
