//
// Created by David Paquette on 12/1/15.
//

#ifndef RTOSOBJECTORIENTEDARDUINO_THREADMANAGER_H
#define RTOSOBJECTORIENTEDARDUINO_THREADMANAGER_H


class ThreadManager {

};


#endif //RTOSOBJECTORIENTEDARDUINO_THREADMANAGER_H
